### PR TITLE
Update live-logs version with description fix

### PR DESCRIPTION
**Pull request by amithins**

### CODE REVIEW

**Comment by eyalbe4** [comment]
@amithins - 

It looks like the the plugin code still includes version 1.0.0, instead of 1.0.1, which failed the release process.
We should probably add this to the list of checks which run on the registry upon creating the a PR.

Anyway, this failed the release. Will you be able to update the version in the code and re-tag?
```
$ git checkout tags/v1.0.1
Note: checking out 'tags/v1.0.1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at e217aa6 Merge pull request #7 from jfrog/fix-plugin-description
$ go build
$ ./live-logs -v
live-logs version v1.0.0
```

**Comment by amithins** [comment]
Sorry, missed this. Have retagged it now.

**Comment by eyalbe4** [comment]
@amithins - 
I can see that v1.0.1 is updated in the plugin code now, but if you build tag v1.0.1, you still get version 1.0.0 when running ```$ ./live-logs -v```.
Maybe you should delete tag v1.0.1, and then recreate it, or alternatively, create tag v1.0.2, and then create a new pull request to the registry with v1.0.2 inside ```live-logs.yml```.

**Comment by amithins** [comment]
The tag was deleted and recreated, let me create v1.0.2.

**Pull request merged**
