### PR TITLE
Adding the metrics-viewer plugin to cli registry

### PR DESCRIPTION
**Pull request by eldada**
I have read the Developer Terms and I hereby accept the terms

### CODE REVIEW

**Comment by eldada** [comment]
I have read the Developer Terms and I hereby accept the terms

**Comment by eyalbe4** [comment]
Congrats @eldada, @noamshemesh and @yinonavraham!
You plugin has been published and can now be installed by running
```
jfrog plugin install metrics-viewer
```
Please go ahead and modify the examples in your plugin's README from ```./metrics-viewer graph``` to ``` jfrog metrics-viewer graph```.
Let's us know when done, and we'll add the plugin to the list of available plugins in the README.
Thanks!

**Comment by eldada** [comment]
Done. README updated @eyalbe4 .

**Comment by eyalbe4** [comment]
Thanks @eldada. You plugin is now included in the list of available plugins.

**Pull request merged**
