### PR TITLE
Adding the Piperika plugin to cli registry

### PR DESCRIPTION
**Pull request by hanochg**

### CODE REVIEW

**Comment by hanochg** [comment]
I have read the Developer Terms and I hereby accept the terms

**Comment by hanochg** [comment]
recheck

**Comment by hanochg** [comment]
recheck

**Comment by hanochg** [comment]
I have read the Developer Terms and I hereby accept the terms

**Comment by hanochg** [comment]
recheck

**Comment by yahavi** [comment]
recheck

**Comment by hanochg** [comment]
I have read the Developer Terms and I hereby accept the terms

**Comment by hanochg** [comment]
recheck

**Comment by hanoch-jfrog** [comment]
I have read the Developer Terms and I hereby accept the terms

**Comment by hanoch-jfrog** [comment]
recheck

**Comment by eyalbe4** [comment]
@hanochg -
Would you like to implement some of the documentation improvements in https://github.com/hanochg/piperika/issues/10 before we merge and publish the plugin?

**Comment by hanochg** [comment]
@eyalbe4 it was implemented, please review the README again :)

**Comment by eyalbe4** [comment]
@hanochg - 
The publication of the plugin failed, because it looks like the plugin's code cannot be built for Windows - 
```
Building piperika.exe for windows-amd64 ...
go: downloading github.com/Microsoft/go-winio v0.4.16
# github.com/buger/goterm
/home/frogger/go/pkg/mod/github.com/buger/goterm@v1.0.3/terminal.go:212:21: undefined: unix.EOPNOTSUPP
```
In order for us to be able to publish the plugin, please go ahead and follow these steps - 
1. Fix the issue in the plugin code.
2. Update the plugin version inside the plugin code.
3. Create a new tag with the new plugin version in the plugin's repository.
3. Create a new PR for this repository, with an update for the ```version``` and ```tag``` properties in ```piperika.yml```.

**Pull request merged**
