### PR TITLE
Add repostats plugin

### PR DESCRIPTION
**Pull request by elioengcomp**
Add repostats plugin to the registry

### CODE REVIEW

**Comment by elioengcomp** [comment]
I have read the Developer Terms and I hereby accept the terms

**Comment by eyalbe4** [comment]
@elioengcomp and @ chanti529,
Thanks for requesting the plugin in the registry!

1. Can you please change the plugin descriptor's extension from **yaml** to **yml**? This is actually the reason why the plugin validation process failed. We've just improved the [Developer Guide](https://github.com/jfrog/jfrog-cli/blob/master/guides/jfrog-cli-plugins-developer-guide.md) so that it reflects this requirement.

2. It looks like commands' flags in the documentation examples are missing a dash. For example, we probably need to replace ```-repos``` with ```--repos```.

3. Can you please make sure that the code is fully covered with tests?
```
eyalb@~/temp/repostats(master)$ go test -v ./...
?   	github.com/chanti529/repostats	[no test files]
?   	github.com/chanti529/repostats/commands	[no test files]
?   	github.com/chanti529/repostats/service	[no test files]
?   	github.com/chanti529/repostats/util	[no test files]
```

4. Notice that ```go vet -v ./...``` fails with the following error:
```
# github.com/chanti529/repostats/service
service/common.go:129:3: unreachable code
```

5. I recommend that you review the "Guidelines for developing and publishing a plugin" in the [Developer Guide](https://github.com/jfrog/jfrog-cli/blob/master/guides/jfrog-cli-plugins-developer-guide.md). This may help you prepare your plugin before going public.

Thank you

**Comment by eyalbe4** [comment]
@elioengcomp and @chanti529,
Are you planning to modify the plugin so that it can be included in the registry?

**Comment by elioengcomp** [comment]
@eyalbe4 unit tests were added and other requested fixes were done.

**Comment by eyalbe4** [comment]
@elioengcomp,

Will you be able to upgrade jfrog-cli-core to v1.5.3 and jfrog-client-go to v0.21.3?
This will fix an issue we had with the displayed plugin description.

Please go ahead and change the "Installation with JFrog CLI" section in the plugin's README, since it will be available for installation with jfrog-cli right after we release it. You can look at the [README of other plugins](https://github.com/jfrog/jfrog-cli-plugins/blob/main/build-deps-info/README.md) included in the registry as a reference 

Please let us know when you're done and we'll add the plugin to the registry.

**Comment by elioengcomp** [comment]
@eyalbe4 done.

**Comment by eyalbe4** [comment]
Congrats @elioengcomp and @chanti529!
Your new **repostats** plugin is now included in the registry and available for installation.

**Pull request merged**
