### PR TITLE
Update live-logs version

### PR DESCRIPTION
**Pull request by shahiinn**
I have read the Developer Terms and I hereby accept the terms

### CODE REVIEW

**Comment by shahiinn** [comment]
recheck

**Comment by shahiinn** [comment]
I have read the Developer Terms and I hereby accept the terms

**Review by amithins — APPROVED** [review]

**Comment by eyalbe4** [comment]
@amithins - 
Please let me know once you fixed the tests, so that I can trigger them again.
Thanks!

**Comment by shahiinn** [comment]
recheck

**Comment by shahiinn** [comment]
@eyalbe4 : Can you please help merging this PR.

**Comment by eyalbe4** [comment]
@shahiinn - 
live-logs v1.0.4 is released!
You can go head and update the [release notes](https://github.com/jfrog/live-logs/blob/main/RELEASE.md).

**Pull request merged**
