### PR TITLE
Updating the metrics-viewer plugin to v0.2.0

### PR DESCRIPTION
**Pull request by eldada**

### CODE REVIEW

**Comment by eyalbe4** [comment]
@eldada  - 
The release of v0.2.0 failed, because it looks like the plugin cannot be built on Windows. This may be result of upgrading go to version 1.16. The code should probably be modified as a result.
Here's how you reproduce the issue - 
```
$ export GOOS=windows
$ export GOARCH=amd64
$ go build
# github.com/buger/goterm
../../go/pkg/mod/github.com/buger/goterm@v1.0.3/terminal.go:212:21: undefined: unix.EOPNOTSUPP
```

**Comment by eldada** [comment]
@eyalbe4 , we will work on this and submit a new PR with the fix.

**Comment by yinonavraham** [comment]
Related to https://github.com/buger/goterm/issues/39

**Comment by yinonavraham** [comment]
Downgrading dependency on `buger/goterm` to `v1.0.1` should solve it.

**Comment by yinonavraham** [comment]
https://github.com/eldada/metrics-viewer/pull/6

**Pull request merged**
